# https://sagiegurari.github.io/cargo-make

extend = "target/rust-driver-makefile.toml"

[env]
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = [
    "xtask",
    "check_hv_vendor",
    "hook_example",
    "shared-contract",
    "win_hv_client",
    "kernel_ssdt",
    "kernel_stealth",
    "kernel_trace",
]

[config]
load_script = '''
#!@rust
//! ```cargo
//! [dependencies]
//! wdk-build = "0.5.1"
//! ```
#![allow(unused_doc_comments)]

wdk_build::cargo_make::load_rust_driver_makefile()?
'''

# Shorten the time needed for `cargo make` by overriding the default with the
# minimal required task.
[tasks.default]
clear = true
dependencies = ["sign-driver-binary"]
